### PR TITLE
Add source service commands

### PR DESCRIPTION
**Pull request by smarlowucf**
Add the commands to install the source service and run the service with osc.

### CODE REVIEW

**Comment by smarlowucf** [comment]
Not sure how best to include these commands. Mentioning osc without previous notes could be confusing to someone who doesn't have osc installed. And explicitly mentioning openSUSE install command leaves out other os's. But maybe there's an assumption if you are in the OBS section that you already have knowledge of OBS/OSC?

**Review by rjschwei — APPROVED** [review]

**Comment by jgleissner** [comment]
> Not sure how best to include these commands. Mentioning osc without previous notes could be confusing to someone who doesn't have osc installed. And explicitly mentioning openSUSE install command leaves out other os's. But maybe there's an assumption if you are in the OBS section that you already have knowledge of OBS/OSC?

We could add a link to https://en.opensuse.org/openSUSE:OSC so people have an easy way to look for information if they are not familiar with osc and how to get the package. The target audience is certainly people who are familiar with OBS though.

**Review by jgleissner — APPROVED** [review]

**Comment by smarlowucf** [comment]
Added a comment directing to the osc docs.

**Comment by jgleissner** [comment]
> Added a comment directing to the osc docs.

Looks good, thanks!

**Pull request merged**
