### PR TITLE
Fix unit tests of OBS src service module

### PR DESCRIPTION
**Pull request by jgleissner**
Fix a previously non functional assertion.
Remove a previously non functional assertion for a function call that was not to be executed in that circumstance anyway.

### CODE REVIEW

**Comment by jgleissner** [comment]
CI tests for python 3.6 are broken at the moment (python 3.6 not supported anymore in used platform), looking into it.

**Comment by rjschwei** [comment]
@jgleissner @apozsuse recently fixed the Python 3.6 unit test issues for other projects we can take the same solution.

**Review by rjschwei — APPROVED** [review]
This also works for me, we just have to be careful not to introduce python 3.6 incompatible syntax as we will no longer catch it during testing.

**Comment by apozsuse** [comment]
> @jgleissner @apozsuse recently fixed the Python 3.6 unit test issues for other projects we can take the same solution.

It was actually Sean that fixed it for some repo (and I extended to other repos having the same issues).

The problem is that python 3.6 is not available any longer in ubuntu:latest container (the one we use for the ci/cd pipeline), and we just splitted the test for 3.6 in a separate job running on ubuntu:20.04.

[Here](https://github.com/SUSE-Enceladus/ec2imgutils/pull/99/files) you can find a PR with that change.

**Comment by jgleissner** [comment]
> The problem is that python 3.6 is not available any longer in ubuntu:latest container (the one we use for the ci/cd pipeline), and we just splitted the test for 3.6 in a separate job running on ubuntu:20.04.

That's what I did too, just a little differently.

**Pull request merged**
