### PR TITLE
Add changelog generator

### PR DESCRIPTION
**Pull request by jgleissner**
Add a script that generaters a changelog (text and yaml format supported) from
the git commit history and the source info log produced by keg.

### CODE REVIEW

**Comment by jgleissner** [comment]
Unit tests are broken. They work locally so this may need some time for debugging.

**Review by rjschwei — APPROVED** [review]

**Comment by jgleissner** [comment]
I see where the problem with the unit tests is. I use real data from the repository's commit log, but in the CILint the commit history isn't available so this fails. Seems I'll have to feed it fake data instead. I guess that's the better option anyway.

**Comment by jgleissner** [comment]
Unit tests are fixed, but it appears the `capture_output` parameter I use with subprocess isn't supported by python 3.6. Compatibility with python 3.6 may not be a bad idea, so I'll look into changing it.

**Comment by jgleissner** [comment]
This should be ok for merge now, another look-over may be not a bad idea. I just noticed an issue with the implementation, namely that it doesn't work with multiple data roots. This should be fixable by storing the data path separately in the source log. I will create a separate PR for that.

**Review by jesusbv — APPROVED** [review]
LGTM

**Review by rjschwei — APPROVED** [review]

**Pull request merged**
