### PR TITLE
Better performance for getting the files

### PR DESCRIPTION
**Pull request by jesusbv**

### CODE REVIEW

**Comment by rjschwei** [comment]
I bet you cannot measure it ;) the better performance I mean. We'd probably have to have 1 million or more files in the tree for this to make a difference.

**Comment by schaefi** [comment]
> I bet you cannot measure it ;) the better performance I mean. We'd probably have to have 1 million or more files in the tree for this to make a difference.

Jesus did measure it, which was the motivation for the change. We had a conversation prior the pull request. Also there is
https://www.python.org/dev/peps/pep-0471/

So this makes sense to me

**Review by schaefi — APPROVED** [review]
looks good to me :+1:

**Comment by jgleissner** [comment]
I don't think this change is particularly useful. I can't imaging os.walk() will be a performance bottleneck with the number of files keg will typically have to deal with. Plus you're introducing recursion, which means the function may throw a maximum recursion exception if the directory tree to be scanned is deeper than the maximum recursion level python allows. Certainly a corner case, but still.

**Pull request merged**
